### PR TITLE
Make tabular work with solph v0.5.0

### PR DESCRIPTION
**Pull request by jnnr**
Adapts tabular to work with the current dev branch of oemof.solph, which will be released as v0.5 soon.
TODO

* [x] Fix constraint tests
* [x] Check that the changes in [33c641c](https://github.com/oemof/oemof-tabular/pull/57/commits/33c641c0ab724000b0b31f26a17c17b47bf53a08) are as expected - not verified yet!
* [x] In solph 0.5, kwargs are explicit and unknown kwargs are not allowed any more. This is the reason for a lot of `TypeError: __init__() got an unexpected keyword argument ...`.  Need to make sure that super().__init__ only receives arguments that it expects. Could be solved together with #44 or separately if that is cleaner.
* [x] This [e2b9e6b](https://github.com/oemof/oemof-tabular/pull/57/commits/e2b9e6bc08673e0baba3f4c69feb28501fef0162) [e6d724a](https://github.com/oemof/oemof-tabular/pull/57/commits/e6d724adb2b9eca30f975c4491d7db33083378ed)is an attempt to pass only expected arguments to the solph component. It has still to be thouroughly thought through, though.
* [x] *args are not used in the init decorated by `kwargs_to_parent`. What to do? [ab4e979](https://github.com/oemof/oemof-tabular/pull/57/commits/ab4e9791fa422dee9e4495bf68df751c12c6a6b9)
* [x] GenericStorage has no custom_attributes. Seems to have been forgotten. https://github.com/oemof/oemof-solph/issues/906 fixed by [e6d724a](https://github.com/oemof/oemof-tabular/pull/57/commits/e6d724adb2b9eca30f975c4491d7db33083378ed) and [ab4e979](https://github.com/oemof/oemof-tabular/pull/57/commits/ab4e9791fa422dee9e4495bf68df751c12c6a6b9)
* [x] Adapt LP files to new pyomo convention especially (`ONE_VAR_CONSTANT`)
* [x] Add LP file sorting, as LP file creation seems not to be reproducible
* [x] Fix `test_emission_constraint`

Depending on changes in `solph v.5.1`:
* [x] Link does not have explicit arguments yet. This does not go well with the adapted init of the dataclasses which checks what the parent's class init expects. Fix by finishing mainline of link.
* [x] Link constraint test fails because the used solph version still has limit_direction with default True. Should be removed, probably by https://github.com/oemof/oemof-solph/pull/888
* [x] Fix link name in flows of LP file. (Will be solved with `oemof.solph v.5.1)

Check if needs to be handled:
* [x] Since https://github.com/oemof/oemof-solph/commit/cd975976073c7734c58c9a38977611cfcf34954c, infinite values are not allowed for nominal value. Tabular uses them at some places, though (for capacity_potential, storage_capacity_potential). The error only refers to the `nominal_value`, therefore this does not affect the named parameters.

Post-processing is not working and will be removed/replaced in #102:
* [ ] Key-error in processing-script as no component is connected to `heat-bus`. Pandas .loc `not found` problem.  [Comment this?](https://github.com/oemof/oemof-tabular/blob/14be04e457e7e0910a7de1ca9e885f793ee5cc24/src/oemof/tabular/examples/scripting/postprocessing.py#LL33C1-L33C1)
* [ ] test_examples:test_scripting_examples fails when postprocessing. More specifically in `set_result_index`. Probably because of the `nan` entry for the last timestep? `Length mismatch: Expected axis has 120 elements, new values have 5 elements`

### CODE REVIEW

**Comment by jnnr** [comment]
Important todo: Check that the changes in [33c641c](https://github.com/oemof/oemof-tabular/pull/57/commits/33c641c0ab724000b0b31f26a17c17b47bf53a08) are as expected.

**Comment by henhuy** [comment]
I just tried to install oemof.solph v0.5.1 (there are two tags `v0.5.1.dev0` and `v0.5.1.dev1`) as dependency, to check whether link test is working:
- In version `v0.5.1.dev0`, link test is still not working due to differences in LP file
- In version `v0.5.1.dev1` all tests are failing due to slightly different results (what's happening there?)

I think this PR should use oemof.solph v0.5.1 as dependency for now (as git dependency) and we should adapt version once oemof.solph v0.5.1 has been released.
I don't know what version will be released (dev0 or dev1), but we should make sure that tabular works with the chosen one.

Regarding the postprocessing tests - I will try to merge new postprocessing, so that we can rebase this branch onto dev and fix/adapt postprocessing tests for solph 0.5

**Review by henhuy — CHANGES_REQUESTED** [review]
In both solph versions `v0.5.1.dev0` and `v0.5.1.dev1` link test is not passing. Even worse, in `v0.5.1.dev1` all tests are failing! (see my comment above about how to face those issues)

**Comment by nailend** [comment]
> I just tried to install oemof.solph v0.5.1 (there are two tags `v0.5.1.dev0` and `v0.5.1.dev1`) as dependency, to check whether link test is working:
> 
> * In version `v0.5.1.dev0`, link test is still not working due to differences in LP file
> * In version `v0.5.1.dev1` all tests are failing due to slightly different results (what's happening there?)
> 
> I think this PR should use oemof.solph v0.5.1 as dependency for now (as git dependency) and we should adapt version once oemof.solph v0.5.1 has been released. I don't know what version will be released (dev0 or dev1), but we should make sure that tabular works with the chosen one.

The test fail due to the mult-period investment which is new in v.0.5.1. This changes the variable names in the LP files. This is easy to fix. Maybe I didn't describe this enough. The link doesn't just work with v5.0.1, the variables still needs to be adjusted. I already tried this locally, the tests will succeed then. I didn't want to blow up this PR, with also adding the multi-period. ITherefore, I suggest not addressing this here but in the PR#105. This PR is already full of a lot of changes in the LP files because of the pyomo update.

**Comment by henhuy** [comment]
Ah I see! Forgot about the Multi-period feature.
It's quite strange, why this big feature will only resolve in a *patch* and not a *minor* version.
IMO fixing link component would be a patch and MP feature a minor update. Whatever...
So, you are right - we should address MP feature in a separate PR

**Review by henhuy — APPROVED** [review]
